---
- name: Verify that the system libraries are installed (Debian)
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - libssl-dev
    - git
  when: ansible_os_family == 'Debian'
  become: true
